#index:
#    path: /
#    controller: App\Controller\DefaultController::index
livraison_generate_pdf:
    path: '/livraison/{id}/generate-pdf'
    controller: App\Controller\LivraisonController::generatePdf